import { chmod, mkdir, open, rename, rm } from 'node:fs/promises';
import path from 'node:path';

import { createLocationAliasCatalog, resolveLocationAlias, type LocationAliasTarget } from '../domain/location-aliases.js';
import type { MullgatePaths } from '../config/paths.js';
import type { MullgateConfig } from '../config/schema.js';
import type { MullvadRelay, MullvadRelayCatalog } from '../mullvad/fetch-relays.js';

const DEFAULT_ALLOWED_IPS = '0.0.0.0/0, ::/0';
const DEFAULT_KEEPALIVE_SECONDS = 25;
const DEFAULT_MULLVAD_DNS = '10.64.0.1';
const DEFAULT_WIREGUARD_PORT = 51820;
const CONTAINER_BIND_HOST = '0.0.0.0';

export type RenderedWireproxyArtifacts = {
  readonly wireproxyConfigPath: string;
  readonly relayCachePath: string;
  readonly configTestReportPath: string;
};

export type RenderWireproxySuccess = {
  ok: true;
  phase: 'artifact-render';
  source: 'canonical-config';
  checkedAt: string;
  selectedRelay: MullvadRelay;
  selectedTarget: LocationAliasTarget | null;
  wireproxyConfig: string;
  artifactPaths: RenderedWireproxyArtifacts;
};

export type RenderWireproxyFailure = {
  ok: false;
  phase: 'artifact-render';
  source: 'canonical-config' | 'relay-catalog' | 'user-input' | 'filesystem';
  checkedAt: string;
  code: 'MISSING_WIREGUARD' | 'NO_MATCHING_RELAY' | 'WRITE_FAILED';
  message: string;
  cause?: string;
  artifactPath?: string;
};

export type RenderWireproxyResult = RenderWireproxySuccess | RenderWireproxyFailure;

export type RenderWireproxyOptions = {
  config: MullgateConfig;
  relayCatalog: MullvadRelayCatalog;
  paths: MullgatePaths;
  generatedAt?: string;
};

export function planWireproxyArtifacts(options: RenderWireproxyOptions): RenderWireproxyResult {
  const checkedAt = options.generatedAt ?? new Date().toISOString();
  const wireguard = options.config.mullvad.wireguard;

  if (!wireguard.publicKey || !wireguard.privateKey || !wireguard.ipv4Address) {
    return {
      ok: false,
      phase: 'artifact-render',
      source: 'canonical-config',
      checkedAt,
      code: 'MISSING_WIREGUARD',
      message: 'Cannot render wireproxy artifacts before Mullvad WireGuard credentials are fully provisioned.',
      artifactPath: options.paths.configFile,
    };
  }

  const selectedTargetResult = resolveConfiguredLocation(options.config, options.relayCatalog.relays);

  if (!selectedTargetResult.ok) {
    return {
      ok: false,
      phase: 'artifact-render',
      source: selectedTargetResult.source,
      checkedAt,
      code: 'NO_MATCHING_RELAY',
      message: selectedTargetResult.message,
      ...(selectedTargetResult.cause ? { cause: selectedTargetResult.cause } : {}),
      artifactPath: selectedTargetResult.artifactPath,
    };
  }

  const selectedRelay = selectedTargetResult.value.relay;
  const wireproxyConfig = buildWireproxyConfig(options.config, selectedRelay, checkedAt);

  return {
    ok: true,
    phase: 'artifact-render',
    source: 'canonical-config',
    checkedAt,
    selectedRelay,
    selectedTarget: selectedTargetResult.value.target,
    wireproxyConfig,
    artifactPaths: {
      wireproxyConfigPath: options.paths.wireproxyConfigFile,
      relayCachePath: options.paths.provisioningCacheFile,
      configTestReportPath: options.paths.wireproxyConfigTestReportFile,
    },
  };
}

export async function renderWireproxyArtifacts(options: RenderWireproxyOptions): Promise<RenderWireproxyResult> {
  const planned = planWireproxyArtifacts(options);

  if (!planned.ok) {
    return planned;
  }

  try {
    await ensureDirectory(options.paths.runtimeDir);
    await ensureDirectory(options.paths.appStateDir);
    await ensureDirectory(options.paths.appCacheDir);

    await writeFileAtomic(planned.artifactPaths.wireproxyConfigPath, planned.wireproxyConfig, 0o600);
    await writeFileAtomic(planned.artifactPaths.relayCachePath, `${JSON.stringify(options.relayCatalog, null, 2)}\n`, 0o600);
  } catch (error) {
    return {
      ok: false,
      phase: 'artifact-render',
      source: 'filesystem',
      checkedAt: planned.checkedAt,
      code: 'WRITE_FAILED',
      message: 'Failed to persist derived wireproxy artifacts under the Mullgate XDG directories.',
      cause: error instanceof Error ? error.message : String(error),
      artifactPath: options.paths.runtimeDir,
    };
  }

  return planned;
}

function buildWireproxyConfig(config: MullgateConfig, relay: MullvadRelay, generatedAt: string): string {
  const wireguard = config.mullvad.wireguard;
  const dnsServers = wireguard.dnsServers.length > 0 ? wireguard.dnsServers : [DEFAULT_MULLVAD_DNS];
  const interfaceAddresses = [wireguard.ipv4Address, wireguard.ipv6Address].filter((value): value is string => Boolean(value));
  const lines = [
    '# Generated by Mullgate. Derived artifact; edit canonical config instead.',
    `# Generated at ${generatedAt}`,
    '',
    '[Interface]',
    `Address = ${interfaceAddresses.join(', ')}`,
    `PrivateKey = ${wireguard.privateKey}`,
    `DNS = ${dnsServers.join(', ')}`,
    '',
    '[Peer]',
    `PublicKey = ${relay.publicKey}`,
    `Endpoint = ${formatRelayEndpoint(relay)}`,
    `AllowedIPs = ${DEFAULT_ALLOWED_IPS}`,
    `PersistentKeepalive = ${DEFAULT_KEEPALIVE_SECONDS}`,
    '',
    '[Socks5]',
    `BindAddress = ${CONTAINER_BIND_HOST}:${config.setup.bind.socksPort}`,
    `Username = ${config.setup.auth.username}`,
    `Password = ${config.setup.auth.password}`,
    '',
    '[http]',
    `BindAddress = ${CONTAINER_BIND_HOST}:${config.setup.bind.httpPort}`,
    `Username = ${config.setup.auth.username}`,
    `Password = ${config.setup.auth.password}`,
  ];

  return `${lines.join('\n')}\n`;
}

function resolveConfiguredLocation(
  config: MullgateConfig,
  relays: readonly MullvadRelay[],
):
  | { ok: true; value: { relay: MullvadRelay; target: LocationAliasTarget | null } }
  | { ok: false; source: 'canonical-config' | 'relay-catalog' | 'user-input'; message: string; cause?: string; artifactPath?: string } {
  const directRelay = findDirectRelayMatch(relays, config);

  if (directRelay) {
    return {
      ok: true,
      value: {
        relay: directRelay,
        target: {
          kind: 'relay',
          hostname: directRelay.hostname,
          fqdn: directRelay.fqdn,
          countryCode: directRelay.location.countryCode,
          countryName: directRelay.location.countryName,
          cityCode: directRelay.location.cityCode,
          cityName: directRelay.location.cityName,
        },
      },
    };
  }

  const aliasInput = config.setup.location.resolvedAlias ?? config.setup.location.hostnameLabel ?? config.setup.location.requested;
  const catalogResult = createLocationAliasCatalog(relays);

  if (!catalogResult.ok) {
    return {
      ok: false,
      source: 'relay-catalog',
      message: 'Mullvad relay metadata could not be normalized into a stable alias catalog.',
      cause: catalogResult.message,
    };
  }

  const resolvedAlias = resolveLocationAlias(catalogResult.value, aliasInput);

  if (!resolvedAlias.ok) {
    return {
      ok: false,
      source: resolvedAlias.source,
      message: 'No relay from the cached Mullvad catalog matched the saved location preference.',
      cause: resolvedAlias.message,
      artifactPath: aliasInput,
    };
  }

  const candidateRelays = relays.filter((relay) => relayMatchesTarget(relay, resolvedAlias.value));
  const constrainedRelays = applyRelayConstraints(candidateRelays, config);
  const selectedRelay = choosePreferredRelay(constrainedRelays);

  if (!selectedRelay) {
    return {
      ok: false,
      source: 'canonical-config',
      message: 'No relay from the cached Mullvad catalog matched the saved location preference.',
      cause: `Resolved alias ${resolvedAlias.alias} but no active relay satisfied the saved constraints.`,
      artifactPath: aliasInput,
    };
  }

  return {
    ok: true,
    value: {
      relay: selectedRelay,
      target: resolvedAlias.value,
    },
  };
}

function findDirectRelayMatch(relays: readonly MullvadRelay[], config: MullgateConfig): MullvadRelay | null {
  const location = config.setup.location;
  const constrained = applyRelayConstraints(relays, config);

  if (location.hostnameLabel) {
    const exactRelay = constrained.find(
      (relay) => relay.hostname === location.hostnameLabel || relay.fqdn === location.hostnameLabel,
    );

    if (exactRelay) {
      return exactRelay;
    }
  }

  if (location.country || location.city) {
    const matchingRelays = constrained.filter((relay) => {
      if (location.country && relay.location.countryCode !== location.country) {
        return false;
      }

      if (location.city && relay.location.cityCode !== location.city) {
        return false;
      }

      return true;
    });

    return choosePreferredRelay(matchingRelays);
  }

  return null;
}

function relayMatchesTarget(relay: MullvadRelay, target: LocationAliasTarget): boolean {
  if (target.kind === 'country') {
    return relay.location.countryCode === target.countryCode;
  }

  if (target.kind === 'city') {
    return relay.location.countryCode === target.countryCode && relay.location.cityCode === target.cityCode;
  }

  return relay.hostname === target.hostname;
}

function applyRelayConstraints(relays: readonly MullvadRelay[], config: MullgateConfig): MullvadRelay[] {
  const providers = new Set(config.mullvad.relayConstraints.providers.map((provider) => provider.toLowerCase()));

  return relays.filter((relay) => {
    if (providers.size > 0 && (!relay.provider || !providers.has(relay.provider.toLowerCase()))) {
      return false;
    }

    return true;
  });
}

function choosePreferredRelay(relays: readonly MullvadRelay[]): MullvadRelay | null {
  const sorted = [...relays].sort(
    (left, right) =>
      Number(right.active) - Number(left.active) ||
      left.location.countryCode.localeCompare(right.location.countryCode) ||
      left.location.cityCode.localeCompare(right.location.cityCode) ||
      left.hostname.localeCompare(right.hostname),
  );

  return sorted[0] ?? null;
}

function formatRelayEndpoint(relay: MullvadRelay): string {
  return `${relay.fqdn}:${relay.multihopPort ?? DEFAULT_WIREGUARD_PORT}`;
}

async function ensureDirectory(directoryPath: string): Promise<void> {
  await mkdir(directoryPath, { recursive: true, mode: 0o700 });
  await chmod(directoryPath, 0o700);
}

async function writeFileAtomic(filePath: string, content: string, mode: number): Promise<void> {
  const directory = path.dirname(filePath);
  const temporaryPath = path.join(directory, `.${path.basename(filePath)}.${process.pid}.${Date.now()}.tmp`);

  let fileHandle;
  try {
    fileHandle = await open(temporaryPath, 'w', mode);
    await fileHandle.writeFile(content, 'utf8');
    await fileHandle.sync();
  } finally {
    await fileHandle?.close();
  }

  try {
    await chmod(temporaryPath, mode);
    await rename(temporaryPath, filePath);
    await chmod(filePath, mode);

    const directoryHandle = await open(directory, 'r');
    try {
      await directoryHandle.sync();
    } finally {
      await directoryHandle.close();
    }
  } catch (error) {
    await rm(temporaryPath, { force: true });
    throw error;
  }
}
