import { normalizeLocationToken } from './location-aliases.js';

const REGION_GROUPS = {
  americas: [
    'ag',
    'ai',
    'ar',
    'aw',
    'bb',
    'bl',
    'bm',
    'bo',
    'br',
    'bs',
    'bz',
    'ca',
    'cl',
    'co',
    'cr',
    'cu',
    'dm',
    'do',
    'ec',
    'fk',
    'gd',
    'gl',
    'gp',
    'gt',
    'gy',
    'hn',
    'ht',
    'jm',
    'kn',
    'ky',
    'lc',
    'mf',
    'mq',
    'ms',
    'mx',
    'ni',
    'pa',
    'pe',
    'pm',
    'pr',
    'py',
    'sr',
    'sv',
    'tc',
    'tt',
    'us',
    'uy',
    'vc',
    've',
    'vg',
    'vi',
  ],
  europe: [
    'ad',
    'al',
    'at',
    'ba',
    'be',
    'bg',
    'by',
    'ch',
    'cy',
    'cz',
    'de',
    'dk',
    'ee',
    'es',
    'fi',
    'fo',
    'fr',
    'gb',
    'gg',
    'gi',
    'gr',
    'hr',
    'hu',
    'ie',
    'im',
    'is',
    'it',
    'je',
    'li',
    'lt',
    'lu',
    'lv',
    'mc',
    'md',
    'me',
    'mk',
    'mt',
    'nl',
    'no',
    'pl',
    'pt',
    'ro',
    'rs',
    'se',
    'si',
    'sj',
    'sk',
    'sm',
    'ua',
    'va',
  ],
  'asia-pacific': [
    'as',
    'au',
    'bd',
    'bn',
    'bt',
    'cc',
    'ck',
    'cn',
    'cx',
    'fj',
    'fm',
    'gu',
    'hk',
    'id',
    'in',
    'jp',
    'kh',
    'ki',
    'kp',
    'kr',
    'la',
    'lk',
    'mh',
    'mm',
    'mn',
    'mo',
    'mp',
    'mv',
    'my',
    'nc',
    'nf',
    'np',
    'nr',
    'nu',
    'nz',
    'pg',
    'ph',
    'pk',
    'pn',
    'pw',
    'sb',
    'sg',
    'th',
    'tk',
    'tl',
    'to',
    'tv',
    'tw',
    'vn',
    'vu',
    'wf',
    'ws',
  ],
  'middle-east-africa': [
    'ae',
    'am',
    'ao',
    'az',
    'bf',
    'bi',
    'bj',
    'bw',
    'cd',
    'cf',
    'cg',
    'ci',
    'cm',
    'cv',
    'dj',
    'dz',
    'eg',
    'eh',
    'er',
    'et',
    'ga',
    'ge',
    'gh',
    'gm',
    'gn',
    'gq',
    'gw',
    'il',
    'iq',
    'ir',
    'jo',
    'ke',
    'km',
    'kw',
    'lb',
    'lr',
    'ls',
    'ly',
    'ma',
    'mg',
    'ml',
    'mr',
    'mu',
    'mw',
    'mz',
    'na',
    'ne',
    'ng',
    'om',
    'qa',
    're',
    'rw',
    'sa',
    'sc',
    'sd',
    'sh',
    'sl',
    'sn',
    'so',
    'ss',
    'st',
    'sz',
    'td',
    'tg',
    'tn',
    'tr',
    'tz',
    'ug',
    'ye',
    'yt',
    'za',
    'zm',
    'zw',
  ],
} as const satisfies Record<string, readonly string[]>;

/**
 * Valid region-group identifier keys supported by the canonical region map.
 */
export type RegionGroupName = keyof typeof REGION_GROUPS;

/**
 * Runtime view of one named region and its normalized country-code membership.
 */
export type RegionGroup = {
  readonly name: RegionGroupName;
  readonly countryCodes: readonly string[];
};

/**
 * Returns the list of available region group names (americas, europe, asia-pacific, middle-east-africa).
 *
 * @returns A frozen array of region group names sorted alphabetically.
 */
export function listRegionGroupNames(): readonly RegionGroupName[] {
  return Object.freeze(Object.keys(REGION_GROUPS).sort() as RegionGroupName[]);
}

/**
 * Returns a list of all available region groups with their names and country codes.
 *
 * @returns A frozen array of RegionGroup objects sorted by name.
 */
export function listRegionGroups(): readonly RegionGroup[] {
  return Object.freeze(
    listRegionGroupNames().map((name) => ({
      name,
      countryCodes: REGION_GROUPS[name],
    })),
  );
}

/**
 * Resolves a region name to its list of country codes.
 *
 * @param region - The region name to resolve (e.g., "americas", "europe", "asia-pacific").
 * @returns A frozen array of country codes, or null if the region is not found.
 */
export function resolveRegionCountryCodes(region: string): readonly string[] | null {
  const normalizedRegion = normalizeLocationToken(region);
  return (REGION_GROUPS as Record<string, readonly string[]>)[normalizedRegion] ?? null;
}
