import { mkdtempSync, statSync } from 'node:fs';
import { readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import { resolveMullgatePaths } from '../../src/config/paths.js';
import { CONFIG_VERSION, type MullgateConfig } from '../../src/config/schema.js';
import { renderRuntimeBundle } from '../../src/runtime/render-runtime-bundle.js';

const temporaryDirectories: string[] = [];

function createTempEnvironment(): NodeJS.ProcessEnv {
  const root = mkdtempSync(path.join(tmpdir(), 'mullgate-runtime-bundle-'));
  temporaryDirectories.push(root);

  return {
    ...process.env,
    HOME: root,
    XDG_CONFIG_HOME: path.join(root, 'config'),
    XDG_STATE_HOME: path.join(root, 'state'),
    XDG_CACHE_HOME: path.join(root, 'cache'),
  };
}

function createFixtureConfig(env: NodeJS.ProcessEnv): MullgateConfig {
  const paths = resolveMullgatePaths(env);
  const timestamp = '2026-03-20T18:48:01.000Z';
  const certPath = path.join(env.HOME!, 'certs', 'proxy.crt');
  const keyPath = path.join(env.HOME!, 'certs', 'proxy.key');

  return {
    version: CONFIG_VERSION,
    createdAt: timestamp,
    updatedAt: timestamp,
    setup: {
      source: 'guided-setup',
      bind: {
        host: '127.0.0.1',
        socksPort: 1080,
        httpPort: 8080,
        httpsPort: 8443,
      },
      auth: {
        username: 'alice',
        password: 'super-secret-password',
      },
      exposure: {
        mode: 'loopback',
        allowLan: false,
      },
      location: {
        requested: 'sweden-gothenburg',
        country: 'se',
        city: 'got',
        resolvedAlias: 'sweden-gothenburg',
      },
      https: {
        enabled: true,
        certPath,
        keyPath,
      },
    },
    mullvad: {
      accountNumber: '123456789012',
      deviceName: 'mullgate-runtime-test',
      lastProvisionedAt: timestamp,
      relayConstraints: {
        providers: [],
      },
      wireguard: {
        publicKey: 'public-key-value',
        privateKey: 'private-key-value',
        ipv4Address: '10.64.12.34/32',
        ipv6Address: 'fc00:bbbb:bbbb:bb01::1:1234/128',
        gatewayIpv4: '10.64.0.1',
        gatewayIpv6: 'fc00:bbbb:bbbb:bb01::1',
        dnsServers: ['10.64.0.1'],
        peerPublicKey: 'peer-public-key-value',
        peerEndpoint: 'se-got-wg-101.relays.mullvad.net:3401',
      },
    },
    runtime: {
      backend: 'wireproxy',
      sourceConfigPath: paths.configFile,
      wireproxyConfigPath: paths.wireproxyConfigFile,
      wireproxyConfigTestReportPath: paths.wireproxyConfigTestReportFile,
      relayCachePath: paths.provisioningCacheFile,
      dockerComposePath: paths.dockerComposePath,
      runtimeBundle: {
        bundleDir: paths.runtimeBundleDir,
        dockerComposePath: paths.runtimeComposeFile,
        httpsSidecarConfigPath: paths.runtimeHttpsSidecarConfigFile,
        manifestPath: paths.runtimeBundleManifestFile,
      },
      status: {
        phase: 'validated',
        lastCheckedAt: timestamp,
        message: 'Fixture config already validated.',
      },
    },
    diagnostics: {
      lastRuntimeStartReportPath: paths.runtimeStartDiagnosticsFile,
      lastRuntimeStart: null,
    },
  };
}

function normalizePaths(value: string, env: NodeJS.ProcessEnv): string {
  return value.split(env.HOME!).join('/tmp/mullgate-home');
}

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })));
});

describe('renderRuntimeBundle', () => {
  it('renders the standalone compose bundle, HAProxy sidecar config, and manifest from canonical settings', async () => {
    const env = createTempEnvironment();
    const paths = resolveMullgatePaths(env);
    const config = createFixtureConfig(env);

    const result = await renderRuntimeBundle({
      config,
      paths,
      generatedAt: '2026-03-20T18:55:00.000Z',
    });

    expect(result.ok).toBe(true);

    if (!result.ok) {
      return;
    }

    const compose = normalizePaths(await readFile(result.artifactPaths.dockerComposePath, 'utf8'), env);
    const httpsSidecarConfig = await readFile(result.artifactPaths.httpsSidecarConfigPath, 'utf8');
    const manifest = normalizePaths(await readFile(result.artifactPaths.manifestPath, 'utf8'), env);
    const composeStats = statSync(result.artifactPaths.dockerComposePath);
    const manifestStats = statSync(result.artifactPaths.manifestPath);

    expect(composeStats.mode & 0o777).toBe(0o600);
    expect(manifestStats.mode & 0o777).toBe(0o600);

    expect('\n' + compose).toMatchInlineSnapshot(`
      "
      # Generated by Mullgate. Derived artifact; edit canonical config instead.
      name: mullgate
      services:
        wireproxy:
          image: backplane/wireproxy:20260320
          user: "0:0"
          restart: unless-stopped
          command:
            - --config
            - /etc/wireproxy/wireproxy.conf
          volumes:
            - /tmp/mullgate-home/state/mullgate/runtime/wireproxy.conf:/etc/wireproxy/wireproxy.conf:ro
          ports:
            - "127.0.0.1:1080:1080"
            - "127.0.0.1:8080:8080"
        https-sidecar:
          image: haproxytech/haproxy-alpine:3.0.19
          restart: unless-stopped
          depends_on:
            - wireproxy
          entrypoint:
            - /bin/sh
            - -ec
            - cat /run/mullgate/tls-input/cert.pem /run/mullgate/tls-input/key.pem > /run/mullgate/tls/haproxy.pem && exec haproxy -W -db -f /usr/local/etc/haproxy/haproxy.cfg
          tmpfs:
            - /run/mullgate/tls
          volumes:
            - /tmp/mullgate-home/state/mullgate/runtime/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
            - /tmp/mullgate-home/certs/proxy.crt:/run/mullgate/tls-input/cert.pem:ro
            - /tmp/mullgate-home/certs/proxy.key:/run/mullgate/tls-input/key.pem:ro
          ports:
            - "127.0.0.1:8443:8443"
      "
    `);
    expect('\n' + httpsSidecarConfig).toMatchInlineSnapshot(`
"\n# Generated by Mullgate. Derived artifact; edit canonical config instead.
global
  log stdout format raw local0

defaults
  log global
  mode tcp
  timeout connect 10s
  timeout client 1m
  timeout server 1m

frontend https_proxy
  bind 0.0.0.0:8443 ssl crt /run/mullgate/tls/haproxy.pem
  default_backend wireproxy_http

backend wireproxy_http
  server wireproxy wireproxy:8080 check
"
`);
    expect('\n' + manifest).toMatchInlineSnapshot(`
"\n{
  \"generatedAt\": \"2026-03-20T18:55:00.000Z\",
  \"source\": \"canonical-config\",
  \"topology\": \"wireproxy-haproxy-sidecar\",
  \"bindHost\": \"127.0.0.1\",
  \"wireproxyConfigPath\": \"/tmp/mullgate-home/state/mullgate/runtime/wireproxy.conf\",
  \"relayCachePath\": \"/tmp/mullgate-home/cache/mullgate/relays.json\",
  \"images\": {
    \"wireproxy\": \"backplane/wireproxy:20260320\",
    \"httpsSidecar\": \"haproxytech/haproxy-alpine:3.0.19\"
  },
  \"services\": {
    \"wireproxy\": {
      \"internalListeners\": {
        \"socks5\": \"0.0.0.0:1080\",
        \"http\": \"0.0.0.0:8080\"
      },
      \"publishedPorts\": [
        \"127.0.0.1:1080:1080\",
        \"127.0.0.1:8080:8080\"
      ]
    },
    \"httpsSidecar\": {
      \"enabled\": true,
      \"internalListener\": \"0.0.0.0:8443\",
      \"publishedPort\": \"127.0.0.1:8443:8443\",
      \"forwardsTo\": \"wireproxy:8080\",
      \"mountPaths\": {
        \"haproxyConfigPath\": \"/tmp/mullgate-home/state/mullgate/runtime/haproxy.cfg\",
        \"certPath\": \"/tmp/mullgate-home/certs/proxy.crt\",
        \"keyPath\": \"/tmp/mullgate-home/certs/proxy.key\",
        \"combinedPemPath\": \"/run/mullgate/tls/haproxy.pem\"
      }
    }
  },
  \"publishedEndpoints\": [
    {
      \"protocol\": \"socks5\",
      \"host\": \"127.0.0.1\",
      \"port\": 1080,
      \"containerHost\": \"0.0.0.0\",
      \"containerPort\": 1080,
      \"auth\": {
        \"username\": \"alice\",
        \"password\": \"[redacted]\"
      },
      \"proxyUrl\": \"socks5://alice:[redacted]@127.0.0.1:1080\"
    },
    {
      \"protocol\": \"http\",
      \"host\": \"127.0.0.1\",
      \"port\": 8080,
      \"containerHost\": \"0.0.0.0\",
      \"containerPort\": 8080,
      \"auth\": {
        \"username\": \"alice\",
        \"password\": \"[redacted]\"
      },
      \"proxyUrl\": \"http://alice:[redacted]@127.0.0.1:8080\"
    },
    {
      \"protocol\": \"https\",
      \"host\": \"127.0.0.1\",
      \"port\": 8443,
      \"containerHost\": \"0.0.0.0\",
      \"containerPort\": 8443,
      \"auth\": {
        \"username\": \"alice\",
        \"password\": \"[redacted]\"
      },
      \"proxyUrl\": \"https://alice:[redacted]@127.0.0.1:8443\"
    }
  ]
}
"
`);
  });

  it('fails when HTTPS is requested without both TLS asset paths', async () => {
    const env = createTempEnvironment();
    const paths = resolveMullgatePaths(env);
    const config = createFixtureConfig(env);
    config.setup.https = { enabled: true, certPath: config.setup.https.certPath };

    const result = await renderRuntimeBundle({
      config,
      paths,
      generatedAt: '2026-03-20T18:56:00.000Z',
    });

    expect(result).toEqual({
      ok: false,
      phase: 'artifact-render',
      source: 'canonical-config',
      checkedAt: '2026-03-20T18:56:00.000Z',
      code: 'MISSING_HTTPS_CONFIG',
      message: 'HTTPS runtime bundle rendering requires both certificate and key paths in the canonical config.',
      artifactPath: config.setup.https.certPath,
    });
  });
});
